name: newsdigest_flutter
description: "NewsDigest AI - AI-powered news summary app"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # 상태관리
  flutter_riverpod: ^2.5.1
  # API 통신
  http: ^1.2.1
  # sqflite DB
  sqflite: ^2.3.3+1
  # 파일 경로
  path_provider: ^2.1.3
  # 경로 처리
  path: ^1.9.0
  # 국제화
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  # 간단 설정 저장
  shared_preferences: ^2.3.2
  # 네비게이션
  go_router: ^14.2.7
  # 반응형 UI
  flutter_screenutil: ^5.9.3
  # 구글 폰트
  google_fonts: ^6.1.0
  # 이미지 캐싱
  cached_network_image: ^3.4.1
  # 공유 가능
  share_plus: ^10.0.2
  # 웹뷰
  webview_flutter: ^4.10.0
  # preview 미리보기
  # device_preview: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true # 국제화 자동생성

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
